openapi: 3.0.1
info:
  title: Borbah API
  version: v1
servers:
  - url: http://localhost/v1
paths:
  /players:
    get:
      summary: Return all player's for the given battle id
      description: Return all player's for the given battle id
      operationId: findAll
      parameters:
        - name: battle
          in: query
          description: battle's id
          required: true
          schema:
            type: string
        - name: sortAsc
          in: query
          description: Should the players be sort in score ascending order
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: Array of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerDto'

    post:
      summary: Create Player with name login
      description: Create Player with name loginPlayer
      operationId: create
      parameters:
        - name: login
          in: query
          description: player's login
          required: true
          schema:
            type: string
        - name: battle
          in: query
          description: the battle id to join
          required: true
          schema:
            type: string
      responses:
        204:
          description: Create Ok

    delete:
      summary: Delete all players
      description: Delete all players
      operationId: delete
      responses:
        204:
          description: Delete ok


  /players/{idPlayer}:
    get:
      summary: Return all informations about a player
      description: Return all informations about a player
      operationId: findById
      parameters:
        - name: idPlayer
          in: path
          description: player's id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the player with idPlayer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDto'
        404:
          description: No player found

    put:
      summary: Update player's score
      description: Update player's score
      operationId: update
      parameters:
        - name: idPlayer
          in: path
          description: player's id
          required: true
          schema:
            type: string
        - name: score
          in: path
          description: player's score
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Update ok

components:
  schemas:
    PlayerDto:
      type: object
      properties:
        idPlayer:
          type: string
          description: Player's id
        login:
          type: string
          description: Player's login
        score:
          type: integer
          description: Player's score
        lastUpdate:
          type: string
          description: Player' score last update
          format: date-time
      description: Player modelisation